/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domain_model.KhachHang;

import java.awt.PopupMenu;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import service.KhachHangService;
import service.impl.KhachHangServiceImpl;

/**
 * @author PhiLT
 */
public class frmChonKhach extends javax.swing.JFrame {

    /**
     * Creates new form frmChonKhach
     */

    private KhachHangService khachHangService = new KhachHangServiceImpl();
    private List<KhachHang> lstKhachHang = new ArrayList<>();
    private DefaultTableModel model;
    private pnBanHang _banHang;

    public frmChonKhach(pnBanHang banHang) {
        initComponents();
        model = (DefaultTableModel) tbKhachHang.getModel();
        _banHang = banHang;

        loadTableKhachHang();
    }

    private void loadTableKhachHang() {
        lstKhachHang = khachHangService.getList();
        model.setRowCount(0);
        for (KhachHang k : lstKhachHang) {
            model.addRow(new Object[]{
                    k.getMaKH(),
                    k.getHoTen(),
                    k.isGioiTinh() + "" == "" ? "" : (k.isGioiTinh() == true ? "Nam" : "Nữ"),
                    k.getDiaChi(),
                    k.getSdt(),
                    k.getEmail(),
                    k.isTrangThai() + "" == "" ? "" : (k.isTrangThai() == true ? "Hoạt động" : "Ngừng hoạt động"),
                    k.getGhiChu()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        chonKhachHang = new javax.swing.JMenuItem();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();

        jPopupMenu1.setPreferredSize(new java.awt.Dimension(200, 30));

        chonKhachHang.setText("Chọn khách");
        chonKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonKhachHangActionPerformed(evt);
            }
        });
        jPopupMenu1.add(chonKhachHang);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jScrollPane3.setBorder(null);

        tbKhachHang.setAutoCreateRowSorter(true);
        tbKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Mã", "Họ và tên", "Giới tính", "Địa chỉ", "SDT", "Email", "Trạng thái", "Ghi chú"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tbKhachHang.setGridColor(new java.awt.Color(255, 255, 255));
        tbKhachHang.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tbKhachHang.setRowHeight(43);
        tbKhachHang.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbKhachHangMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbKhachHang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbKhachHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhachHangMouseReleased
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3) {
            if (evt.isPopupTrigger() && tbKhachHang.getSelectedRowCount() != 0) {
                jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tbKhachHangMouseReleased

    private void chonKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonKhachHangActionPerformed
        // TODO add your handling code here:
        int row = tbKhachHang.getSelectedRow();
        if (row != -1) {
            int selectedRow = tbKhachHang.getSelectedRow();
            String ma = tbKhachHang.getValueAt(selectedRow, 0) + "";
            for (KhachHang k : lstKhachHang) {
                if (k.getMaKH().equals(ma)) {
                    _banHang.getKhachHang(k);
                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_chonKhachHangActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem chonKhachHang;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTable tbMauSac;
    private javax.swing.JTable tbMauSac1;
    // End of variables declaration//GEN-END:variables
}
