/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domain_model.NhanVien;

import java.util.List;
import javax.swing.table.DefaultTableModel;

import service.NhanVienService;
import service.impl.NhanVienServiceImpl;

/**
 * @author Admin
 */
public class panelQuanLyNhanVien extends javax.swing.JPanel {

    private final NhanVienService nhanVienService;

    /**
     * Creates new form panelQuanLyNhanVien
     */
    public panelQuanLyNhanVien() {
        initComponents();

        nhanVienService = new NhanVienServiceImpl();

        loadTable(nhanVienService.getAll());
        loadCBBChucVu();
        loadCBBTrangThai();
    }

    private void loadTable(List<NhanVien> list) {

        DefaultTableModel dtm = (DefaultTableModel) this.tableNhanVien.getModel();
        dtm.setRowCount(0);
        for (NhanVien nv : list) {
            Object[] rowData = {
                    nv.getIdNhanVien(),
                    nv.getMaNhanVien(),
                    nv.getHoTenNhanVien(),
                    nv.isGioiTinh(),
                    nv.getDiaChi(),
                    nv.getSDT(),
                    nv.getEmail(),
                    nv.getCccd(),
                    nv.getTenTK(),
                    nv.getPass(),
                    nv.getChucVu(),
                    nv.getGhiChu(),
                    nv.getTrangThai() == null ? "" : (nv.getTrangThai() == true ? "Hoạt động" : "Nghỉ việc")
            };
            dtm.addRow(rowData);
        }
    }

    private void loadCBBChucVu() {
        cbbChucVu.removeAllItems();
        cbbChucVu.addItem("Quản lý");
        cbbChucVu.addItem("Nhân viên");
    }

    private void loadCBBTrangThai() {
        cbbTrangThai.removeAllItems();

        cbbTrangThai.addItem("Nghỉ việc");
        cbbTrangThai.addItem("Hoạt động");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JTextField();
        txtCccd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taGhiChu = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtTenTK = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        cbbChucVu = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbbTrangThai = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(1322, 743));
        jPanel1.setPreferredSize(new java.awt.Dimension(1275, 790));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null, null, null}
                },
                new String[]{
                        "ID", "Mã", "Họ và tên", "Giới tính", "Địa chỉ", "SDT", "Email", "cccd", "Tk", "Mật khẩu", "Chức vụ", "Ghi chú", "Trạng thái"
                }
        ));
        tableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableNhanVien);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1250, 340));

        jLabel1.setText("Họ tên");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));
        jPanel1.add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 329, -1));

        jLabel2.setText("Giới tính");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));
        jPanel1.add(txtGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 329, -1));
        jPanel1.add(txtCccd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 329, -1));

        jLabel4.setText("Địa chỉ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        jLabel5.setText("SDT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        taGhiChu.setColumns(20);
        taGhiChu.setRows(5);
        jScrollPane1.setViewportView(taGhiChu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 630, 329, 70));

        jLabel6.setText("Tên tài khoản");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, -1, -1));

        jLabel8.setText("Mật khẩu");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, -1));

        jLabel9.setText("CCCD ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, -1, -1));

        jLabel11.setText("Ghi chú");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 630, -1, -1));

        jLabel12.setText("Chức vụ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, -1, -1));

        btnUpdate.setText("Thêm");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 730, -1, -1));

        jLabel14.setText("Email");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, -1, -1));

        pass.setText("password");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 330, -1));
        jPanel1.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 329, -1));
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, 329, -1));
        jPanel1.add(txtTenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 329, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 329, -1));

        btnThem.setText("Update");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 730, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Nhân viên");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel7.setText("Mã");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));
        jPanel1.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 329, -1));

        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jPanel1.add(cbbChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 110, -1));

        jLabel10.setText("Trạng thái");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, -1, -1));

        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jPanel1.add(cbbTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 590, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1270, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 810, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNhanVienMouseClicked
        // TODO add your handling code here:
        int row = tableNhanVien.getSelectedRow();
        NhanVien nv = nhanVienService.getAll().get(row);
        txtMaNV.setText(nv.getMaNhanVien());
        txtTenNV.setText(nv.getHoTenNhanVien());
        txtDiaChi.setText(nv.getDiaChi());
        txtTenTK.setText(nv.getTenTK());
        pass.setText(nv.getPass());
        txtEmail.setText(nv.getEmail());
        txtSDT.setText(nv.getSDT());
        txtCccd.setText(nv.getCccd());
        cbbChucVu.setSelectedIndex(nv.getChucVu() == 1 ? 0 : 1);
        taGhiChu.setText(nv.getGhiChu());
        cbbTrangThai.setSelectedIndex(nv.getTrangThai() == true ? 1 : 0);
    }//GEN-LAST:event_tableNhanVienMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        NhanVien nv = new NhanVien();
        nv.setHoTenNhanVien(txtTenNV.getText());
        nv.setGioiTinh(Boolean.parseBoolean(txtGioiTinh.getText()));
        nv.setDiaChi(txtDiaChi.getText());
        nv.setSDT(txtSDT.getText());
        nv.setTenTK(txtTenTK.getText());
        nv.setPass(pass.getText());
        nv.setEmail(txtEmail.getText());
        nv.setCccd(txtCccd.getText());
        nv.setChucVu(cbbChucVu.getSelectedIndex() == 0 ? 1 : 2);
        nv.setGhiChu(taGhiChu.getText());
        nv.setTrangThai(cbbTrangThai.getSelectedIndex() == 0 ? false : true);
        nhanVienService.add(nv);
        loadTable(nhanVienService.getAll());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        int row = tableNhanVien.getSelectedRow();
        NhanVien nv = nhanVienService.getAll().get(row);

        nv.setMaNhanVien(txtMaNV.getText());
        nv.setHoTenNhanVien(txtTenNV.getText());
        nv.setGioiTinh(Boolean.parseBoolean(txtGioiTinh.getText()));
        nv.setDiaChi(txtDiaChi.getText());
        nv.setSDT(txtSDT.getText());
        nv.setTenTK(txtTenTK.getText());
        nv.setPass(pass.getText());
        nv.setEmail(txtEmail.getText());
        nv.setCccd(txtCccd.getText());
        nv.setChucVu(cbbChucVu.getSelectedIndex() == 0 ? 1 : 2);
        nv.setGhiChu(taGhiChu.getText());
        nv.setTrangThai(cbbTrangThai.getSelectedIndex() == 0 ? false : true);
        nhanVienService.update(nv);
        loadTable(nhanVienService.getAll());
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextArea taGhiChu;
    private javax.swing.JTable tableNhanVien;
    private javax.swing.JTextField txtCccd;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenTK;
    // End of variables declaration//GEN-END:variables
}
