/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;


import Piechart.ModelPieChart;
import Piechart.PieChart;

import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.table.DefaultTableModel;

import repository.DoanhThuRepo;
import repository.DoanhThuRepoImpl;


/**
 * @author PhiLT
 */
public class pnThongKe extends javax.swing.JPanel {
    //MessagePane MSG = new MessagePane();


    private DoanhThuRepo doanhThuRepo = new DoanhThuRepoImpl();

    public pnThongKe() {
        initComponents();

        modelTBDoanhThu = (DefaultTableModel) tbDoanhThu.getModel();

        loadCBBAllNam();
        loadCBBAllThang();
        setDoanhThuHomNay();
    }

    //Doanh thu hom nay
    private void setDoanhThuHomNay() {
        String doanhThuHomNay = doanhThuRepo.getDoanhThuHomNay() == null ? "0" : format.format(doanhThuRepo.getDoanhThuHomNay()) + "";
        lbDoanhThuHomNay.setText(doanhThuHomNay + " đồng");
    }

    //set combobox
    private List<Integer> lstNam = new ArrayList<>();
    private List<Integer> lstThang = new ArrayList<>();

    private void loadCBBAllNam() {
        lstNam = doanhThuRepo.getAllNam();
        cbbAllNam.removeAllItems();
        for (Integer i : lstNam) {
            cbbAllNam.addItem(i + "");
        }
        loadCBBAllThang();
    }

    private void loadCBBAllThang() {
        lstThang = doanhThuRepo.getAllThang(Integer.parseInt(cbbAllNam.getSelectedItem().toString()));
        cbbAllThang.removeAllItems();
        for (Integer i : lstThang) {
            cbbAllThang.addItem(i + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDoanhThu = new javax.swing.JTable();
        pieChart1 = new Piechart.PieChart();
        lbTongDoanhSo = new javax.swing.JLabel();
        lbTongLN = new javax.swing.JLabel();
        lbDoanhSo = new javax.swing.JLabel();
        lbDoanhThu = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbDoanhThuNam = new javax.swing.JLabel();
        cbbAllNam = new javax.swing.JComboBox<>();
        cbbAllThang = new javax.swing.JComboBox<>();
        lbDoanhThuHomNay = new javax.swing.JLabel();
        lbDoanhThuThang = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setEnabled(false);
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(1322, 743));
        setPreferredSize(new java.awt.Dimension(1275, 790));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Thống kê");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 90, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);

        tbDoanhThu.setAutoCreateRowSorter(true);
        tbDoanhThu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String[]{
                        "Tháng", "Doanh thu", "Lợi nhuận"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tbDoanhThu.setGridColor(new java.awt.Color(255, 255, 255));
        tbDoanhThu.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tbDoanhThu.setRowHeight(43);
        tbDoanhThu.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tbDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDoanhThuMouseClicked(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbDoanhThuMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbDoanhThu);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 700, 640));

        lbTongDoanhSo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTongDoanhSo.setForeground(new java.awt.Color(102, 102, 102));
        lbTongDoanhSo.setText("0");
        pieChart1.add(lbTongDoanhSo);
        lbTongDoanhSo.setBounds(180, 550, 170, 30);

        lbTongLN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTongLN.setForeground(new java.awt.Color(102, 102, 102));
        lbTongLN.setText("0");
        pieChart1.add(lbTongLN);
        lbTongLN.setBounds(410, 550, 220, 30);

        jPanel3.add(pieChart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 670, 580));

        lbDoanhSo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDoanhSo.setForeground(new java.awt.Color(60, 63, 65));
        lbDoanhSo.setText("Doanh số");
        jPanel3.add(lbDoanhSo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 400, 30));

        lbDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDoanhThu.setForeground(new java.awt.Color(60, 63, 65));
        lbDoanhThu.setText("Doanh thu");
        jPanel3.add(lbDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 300, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1460, 680));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Doanh thu");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Doanh thu năm");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Doanh thu tháng ");

        lbDoanhThuNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDoanhThuNam.setForeground(new java.awt.Color(102, 102, 102));
        lbDoanhThuNam.setText("Doanh thu hôm nay");

        cbbAllNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        cbbAllNam.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbbAllNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbAllNamActionPerformed(evt);
            }
        });

        cbbAllThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        cbbAllThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbAllThangActionPerformed(evt);
            }
        });

        lbDoanhThuHomNay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDoanhThuHomNay.setForeground(new java.awt.Color(102, 102, 102));
        lbDoanhThuHomNay.setText("0");

        lbDoanhThuThang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDoanhThuThang.setForeground(new java.awt.Color(102, 102, 102));
        lbDoanhThuThang.setText("Doanh thu hôm nay");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Doanh thu hôm nay");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbbAllNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbDoanhThuNam))
                                .addGap(251, 251, 251)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDoanhThuThang)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbbAllThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDoanhThuHomNay)
                                        .addComponent(jLabel20))
                                .addGap(202, 202, 202))
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel17)
                                        .addComponent(cbbAllNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbbAllThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbDoanhThuNam)
                                        .addComponent(lbDoanhThuThang)
                                        .addComponent(lbDoanhThuHomNay))
                                .addGap(0, 45, Short.MAX_VALUE))
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1460, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void tbDoanhThuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDoanhThuMouseReleased
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3) {
            if (evt.isPopupTrigger() && tbDoanhThu.getSelectedRowCount() != 0) {
                return;
            }
        }
    }//GEN-LAST:event_tbDoanhThuMouseReleased

    private void cbbAllNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbAllNamActionPerformed
        // TODO add your handling code here:
        if (cbbAllNam.getSelectedIndex() != -1) {
            int namSelect = Integer.parseInt(cbbAllNam.getSelectedItem().toString());
            loadTableDTNam(namSelect);
            loadDataDoanhSoNam(namSelect);
            lbDoanhThu.setText("Doanh thu năm " + namSelect);
        }
    }//GEN-LAST:event_cbbAllNamActionPerformed

    private void cbbAllThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbAllThangActionPerformed
        // TODO add your handling code here:
        if (cbbAllThang.getSelectedIndex() != -1) {
            int namSelect = Integer.parseInt(cbbAllNam.getSelectedItem().toString());
            int thangSelect = Integer.parseInt(cbbAllThang.getSelectedItem().toString());
            loadTableDTThang(namSelect, thangSelect);
            loadDataDoanhSoThang(namSelect, thangSelect);
            lbDoanhThu.setText("Doanh thu tháng " + thangSelect + ", năm " + namSelect);
        }
    }//GEN-LAST:event_cbbAllThangActionPerformed

    private void tbDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDoanhThuMouseClicked
        // TODO add your handling code here:
        String check = tbDoanhThu.getColumnName(0);
        int rowSelect = tbDoanhThu.getSelectedRow();
        String timeSales = tbDoanhThu.getValueAt(rowSelect, 0).toString();
        int yearTime = Integer.parseInt(cbbAllNam.getSelectedItem().toString());
        if (check.equals("Tháng")) {

            loadDataDoanhSoThang(yearTime, Integer.parseInt(timeSales));
        }
        if (check.equals("Ngày")) {
            int monthTime = Integer.parseInt(cbbAllThang.getSelectedItem().toString());
            loadDataDoanhSoNgay(yearTime, monthTime, Integer.parseInt(timeSales));
        }
    }//GEN-LAST:event_tbDoanhThuMouseClicked

    //load table
    private DefaultTableModel modelTBDoanhThu;
    private List<Object[]> lstDTNam = new ArrayList<>();
    private List<Object[]> lstDTThang = new ArrayList<>();
    private final DecimalFormat format = new DecimalFormat("#,##0.#");

    private void loadTableDTNam(int nam) {

        BigDecimal tongDT = BigDecimal.valueOf(Float.parseFloat(0 + ""));

        modelTBDoanhThu.setColumnCount(0);
        modelTBDoanhThu.addColumn("Tháng");
        modelTBDoanhThu.addColumn("Doanh thu");
        modelTBDoanhThu.addColumn("Lợi nhuận");
        modelTBDoanhThu.setRowCount(0);
        lstDTNam = doanhThuRepo.getDoanhThuNam(nam);
        for (Object[] o : lstDTNam) {
            tongDT = tongDT.add((BigDecimal) o[1]);
            modelTBDoanhThu.addRow(new Object[]{
                    o[0],
                    o[1] + " đồng",
                    o[2] + " đồng"
            });
        }
        lbDoanhThuNam.setText(format.format(tongDT) + " đồng");
    }


    private void loadTableDTThang(int nam, int thang) {

        BigDecimal tongDT = BigDecimal.valueOf(Float.parseFloat(0 + ""));

        modelTBDoanhThu.setColumnCount(0);
        modelTBDoanhThu.addColumn("Ngày");
        modelTBDoanhThu.addColumn("Doanh thu");
        modelTBDoanhThu.addColumn("Lợi nhuận");
        modelTBDoanhThu.setRowCount(0);
        lstDTThang = doanhThuRepo.getDoanhThuThang(nam, thang);
        for (Object[] o : lstDTThang) {
            tongDT = tongDT.add((BigDecimal) o[1]);
            modelTBDoanhThu.addRow(new Object[]{
                    o[0],
                    o[1] + " đồng",
                    o[2] + " đồng"
            });
        }
        lbDoanhThuThang.setText(format.format(tongDT) + " đồng");
    }

    //load doanh số
    private List<Object[]> lstDoanhSo = new ArrayList<>();

    private void loadDataDoanhSoNam(int nam) {
        lstDoanhSo = doanhThuRepo.getDoanhSoNam(nam);
        loadDataDoanhSo();
        lbDoanhSo.setText("Doanh số " + "năm " + nam);
    }

    private void loadDataDoanhSoThang(int nam, int thang) {
        lstDoanhSo = doanhThuRepo.getDoanhSoThang(nam, thang);
        loadDataDoanhSo();
        lbDoanhSo.setText("Doanh số tháng" + " " + thang + ", năm " + nam);
    }

    private void loadDataDoanhSoNgay(int nam, int thang, int ngay) {
        lstDoanhSo = doanhThuRepo.getDoanhSoNgay(nam, thang, ngay);
        loadDataDoanhSo();
        lbDoanhSo.setText("Doanh số ngày" + " " + ngay + ", tháng " + thang + ", năm " + nam);
    }

    private void loadDataDoanhSo() {
        BigDecimal tongLN = BigDecimal.valueOf(Double.parseDouble("0"));
        int tongds = 0;
        pieChart1.setChartType(PieChart.PeiChartType.DONUT_CHART);


        if (lstDoanhSo.isEmpty()) return;

        pieChart1.clearData();
        for (int j = 0; j < lstDoanhSo.size(); j++) {
            tongds += Integer.parseInt(lstDoanhSo.get(j)[1] + "");
            tongLN = tongLN.add((BigDecimal) lstDoanhSo.get(j)[2]);
            pieChart1.addData(new ModelPieChart(lstDoanhSo.get(j)[0].toString(), Double.parseDouble(lstDoanhSo.get(j)[1] + ""), Double.parseDouble(lstDoanhSo.get(j)[2] + ""), new java.awt.Color(j, ThreadLocalRandom.current().nextInt(j, 225), ThreadLocalRandom.current().nextInt(j, 200))));
        }
        lbTongDoanhSo.setText("Tổng cộng: " + tongds + " đôi");
        lbTongLN.setText("Lợi nhuận: " + format.format(tongLN) + " đồng");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbAllNam;
    private javax.swing.JComboBox<String> cbbAllThang;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDoanhSo;
    private javax.swing.JLabel lbDoanhThu;
    private javax.swing.JLabel lbDoanhThuHomNay;
    private javax.swing.JLabel lbDoanhThuNam;
    private javax.swing.JLabel lbDoanhThuThang;
    private javax.swing.JLabel lbTongDoanhSo;
    private javax.swing.JLabel lbTongLN;
    private Piechart.PieChart pieChart1;
    private javax.swing.JTable tbDoanhThu;
    // End of variables declaration//GEN-END:variables
}
